### PR TITLE
docs: switch to “email” spelling

### PR DESCRIPTION
**Pull request by j9t**
Signed-off-by: Jens Oliver Meiert <jens@meiert.com>

### CODE REVIEW

**Comment by j9t** [comment]
Hi @lkisoslive—can you review and, unless there’s a problem with the changes, approve? (Thanks!)

**Comment by lkisoslive** [comment]
Sure thing.

On Mon, Aug 15, 2022 at 11:49 AM Jens Oliver Meiert <
***@***.***> wrote:

> Hi @lkisoslive
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lkisoslive&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=ShrVgFLLAuzR8snVbrQkmq_9bmUP0A_cY3KBwAkUQBA&m=5l5nQv9cqGu_lN-ApA_znCjiuWY5aGN7TtHeLgWfxy3skjNuelSwFm2JRH49lm6w&s=awrOHSD8W8sqwGn51ih_hdKIi0iffyAGmzwWwFSVqzI&e=>—can
> you review and, unless there’s a problem with the changes, approve?
> (Thanks!)
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developer-2Dcenter_pull_1808-23issuecomment-2D1214765861&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=ShrVgFLLAuzR8snVbrQkmq_9bmUP0A_cY3KBwAkUQBA&m=5l5nQv9cqGu_lN-ApA_znCjiuWY5aGN7TtHeLgWfxy3skjNuelSwFm2JRH49lm6w&s=ij14SRLSysH4sx7rMQ7Lebc_NEMnWFqZ1UsdfEHnzSQ&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AU3MSSBUVF4DCXXGE6M5GI3VZIADHANCNFSM56IGL4BA&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=ShrVgFLLAuzR8snVbrQkmq_9bmUP0A_cY3KBwAkUQBA&m=5l5nQv9cqGu_lN-ApA_znCjiuWY5aGN7TtHeLgWfxy3skjNuelSwFm2JRH49lm6w&s=Zu4pXIbVdRKoyj64Jku6vI2zIXnkKNS7alc8yQ7DaEU&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Review by lkisoslive — APPROVED** [review]
A few minor changes

**Comment by j9t** [comment]
Thanks @lkisoslive; incorporated your suggestion.

**Pull request merged**
