### PR TITLE
Improved print styling (and cleaned up style sheets)

### PR DESCRIPTION
**Pull request by j9t**
Closes DX-125 (and resolves parts of DX-77)

@itay1313, was the latest Gemfile.lock checked in? I’m surprised this changed on my end; committing the update as everything worked locally.

Please note the cleaned up print layout… I couldn’t spot anything that would use it, but perhaps you know more.

### CODE REVIEW

**Review by itay1313 — APPROVED** [review]

**Comment by j9t** [comment]
(@itay1313, this can wait until you’re back :)

**Comment by itay1313** [comment]
@j9t  please merge this branch, 
there is a problem with the build with   jekyll-last-modified-at 
i saw that my new latest post update is not in production so i checked and it looks like in platform the build are failing so this fix is good, please merge it, let's see that in platform the build will work.

**Comment by j9t** [comment]
@itay1313—merged. If possible, let’s keep an eye on this and that it goes live okay.

**Comment by itay1313** [comment]
yes, it worked, now i can see everything is up to date
https://developers.liveperson.com/getting-started-with-your-free-trial-account.html

great,
 night :)

**Pull request merged**
